# Generated by Django 4.2.7 on 2023-12-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basesum',
            old_name='percent',
            new_name='sum',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='spots_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parking',
            name='total_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
