# Generated by Django 4.2.7 on 2023-12-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_employeeofparking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_sum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.basesum')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
