# Generated by Django 4.2.7 on 2023-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsum',
            name='sum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
