# Generated by Django 4.2.7 on 2023-12-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingsum_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ended',
        ),
    ]
