# Generated by Django 4.2.7 on 2023-12-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password2',
            new_name='repeat_password',
        ),
    ]
