# Generated by Django 4.2.7 on 2023-12-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
