# Generated by Django 4.2.7 on 2023-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
